version: '3'
services:
  db:
    build: ./db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'platzi'
      POSTGRES_DB: 'pizza'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "6437:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data: